blank_issues_enabled: false
contact_links:
  - name: Installation/Running Issues
    url: https://discord.gg/trZgYNmrQf
    about: If you are having issues installing or running the mod, please join the Discord here